name: projecommerce
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-31.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  animate_do: ^3.3.4
  uuid: ^4.4.0
  fluttertoast: ^8.2.5
  cloud_firestore: ^4.15.8
  adaptive_theme: ^3.6.0
  animated_expandable_fab: ^0.0.3
  item_count_number_button: ^1.9.2
  loading_icon_button: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
   - assets/images/

